version: "3.8"
services:
  server:
    build:
      context: .
      args:
        user: $USER
        uid: 1000
        gid: 1000
        APP_ENV: $APP_ENV
    image: rosem:${APP_VERSION:-latest}
    container_name: rosem-server
    volumes:
      - ./:/var/www
      - $HOME/.composer:/home/$USER/.composer
      - ./docker/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    ports:
      - ${CONTAINER_IP:-127.0.0.1}:80:80
      - ${CONTAINER_IP:-127.0.0.1}:443:443
      - ${CONTAINER_IP:-127.0.0.1}:8000:8000
    networks:
      - rosem
networks:
  rosem:
    driver: bridge
