version: "3.8"
services:
  server:
    build:
      context: ./
      args:
        user: $USER
    image: rosem:${APP_VERSION:-latest}
    container_name: rosem-server
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - $HOME/.composer:/home/$USER/.composer
      - ./docker/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
    ports:
      - ${CONTAINER_IP:-127.0.0.1}:80:80
      - ${CONTAINER_IP:-127.0.0.1}:443:443
      - ${CONTAINER_IP:-127.0.0.1}:8000:8000
    networks:
      - rosem
networks:
  rosem:
    driver: bridge
